---
title: "Modelling Results"
author: "Andreas Hansen"
date: "2023-05-08"
output: html_document
---

```{r}
Result_table <- data.frame(model = character(), free_arima = character(), seasonal = character(), free_seasonal = character(), xreg = character(), RMSE = double(), stringsAsFactors = FALSE)
```

```{r}
Result_table <- rbind(Result_table, list("Linear Regression", "", "", "", "", 499.7))
Result_table <- rbind(Result_table, list("Sinusoidal Regression", "", "", "", "", 847.4))
Result_table <- rbind(Result_table, list("Sum of Sinusoidal Regressions", "", "", "", "", 1535.0))
Result_table <- rbind(Result_table, list("ARIMA(1,1,0)", "", "", "", "", 431.5))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "24th", "", "", "", 417.5))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "", 371.8))
Result_table <- rbind(Result_table, list("SARIMA(24,1,0)", "24th", "(7,0,0)", "1st, 2nd, 7th", "", 380.9))
Result_table <- rbind(Result_table, list("SARIMA(24,1,0)", "", "(7,0,0)", "", "", 362.7))
Result_table <- rbind(Result_table, list("SARIMA(1,1,0)", "", "(7,0,0)", "1st, 2nd, 7th", "", 388.8))
Result_table <- rbind(Result_table, list("SARIMA(1,1,0)", "", "(7,0,0)", "", "", 368.0))
Result_table <- rbind(Result_table, list("SARIMA(24,1,0)", "", "(7,1,0)", "", "", 363.7))
Result_table <- rbind(Result_table, list("SARIMA(24,1,1)", "", "(7,0,0)", "", "", 369.2))
Result_table <- rbind(Result_table, list("SARIMA(24,1,1)", "24th", "(7,0,0)", "", "", 362.5))
Result_table <- rbind(Result_table, list("SARIMA(24,1,1)", "24th", "(7,0,0)", "1st, 2nd, 7th", "", 381.2))
Result_table <- rbind(Result_table, list("SARIMA(24,1,1)", "", "(7,0,1)", "", "", 344.0))
Result_table <- rbind(Result_table, list("SARIMA(24,1,1)", "24th", "(7,0,1)", "", "", 362.0))
Result_table <- rbind(Result_table, list("SARIMA(24,1,1)", "", "(7,0,1)", "1st, 2nd, 7th", "", 356.7))
Result_table <- rbind(Result_table, list("SARIMA(24,1,1)", "24th", "(7,0,1)", "1st, 2nd, 7th", "", 356.7))
Result_table <- rbind(Result_table, list("SARIMA(24,1,24)", "", "(7,0,0)", "", "", 346.6))
Result_table <- rbind(Result_table, list("SARIMA(24,1,24)", "", "(7,0,7)", "", "", 361.2))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend", 366.3))
Result_table <- rbind(Result_table, list("SARIMA(24,1,1)", "", "(7,0,1)", "", "Weekend", 341.2))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekdays", 365.0))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Season", 366.4))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Wind", 316.8))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Wind, Solar", 318.6))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, FossilProduce", 347.7))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Wind, FossilProduce", 305.8))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Wind, FossilProduce, Consumption", 305.2))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Wind, FossilProduce, Biomass", 302.4))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Wind, FossilProduce, Biomass, Waste", 299.4))
Result_table <- rbind(Result_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Wind, FossilProduce, Biomass, Waste, Exchange", 276.1))
Result_table <- rbind(Result_table, list("ARIMA(1,1,0)", "", "", "", "Weekend, Wind, FossilProduce, Biomass, Waste, Exchange", 303.5))
Result_table <- rbind(Result_table, list("SARIMA(24,1,0)", "24th", "(7,0,0)", "1st, 2nd, 7th", "Weekend, Wind, FossilProduce, Biomass, Waste, Exchange", 311.8))
Result_table <- rbind(Result_table, list("SARIMA(24,1,1)", "", "(7,0,1)", "", "Weekend, Wind, FossilProduce, Biomass, Waste, Exchange", 263.9))
Result_table <- rbind(Result_table, list("auto.arima(23,1,0)", "", "", "", "", 369.8))
Result_table <- rbind(Result_table, list("auto.arima(23,1,0)", "", "", "", "Weekend, Wind, FossilProduce, Biomass, Waste, Exchange", 262.3))
colnames(Result_table) <- c("model", "free_arima", "seasonal", "free_seasonal", "xreg", "RMSE")
```

```{r}
CV_table <- data.frame(model = character(), free_arima = character(), seasonal = character(), free_seasonal = character(), xreg = character(), RMSE_subset_1 = double(), RMSE_subset_2 = double(), RMSE_subset_3 = double(), RMSE_subset_4 = double(), mean_RMSE = double(), sd_RMSE = double(), stringsAsFactors = FALSE)
```

```{r}
CV_table <- rbind(CV_table, list("ARIMA(24,1,0)", "", "", "", "", 441.3, 704.8, 442.1, 371.0, 489.8, 147.2))
CV_table <- rbind(CV_table, list("SARIMA(24,1,1)", "", "(7,0,1)", "", "", 393.3, 661.9, 391.7, 342.1, 447.3, 145.1))
CV_table <- rbind(CV_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Wind", 354.6, 674.8, 405.2, 364.3, 449.7, 151.6))
CV_table <- rbind(CV_table, list("ARIMA(24,1,0)", "", "", "", "Weekend, Wind, FossilProduce, Biomass, Waste, Exchange", 240.9, 543.2, 328.5, 364.3, 369.2, 127.1))
CV_table <- rbind(CV_table, list("SARIMA(24,1,1)", "", "(7,0,1)", "", "Weekend, Wind, FossilProduce, Biomass, Waste, Exchange", 233.0, 539.5, 316.7, 337.7, 356.7, 130.0))
CV_table <- rbind(CV_table, list("auto.arima(23,1,0)", "", "", "", "Weekend, Wind, FossilProduce, Biomass, Waste, Exchange", 240.5, 533.7, 345.2, 359.4, 369.7, 121.5))
colnames(CV_table) <- c("model", "free_arima", "seasonal", "free_seasonal", "xreg", "sub_RMSE_1", "sub_RMSE_2", "sub_RMSE_3", "sub_RMSE_4", "mean_RMSE", "sd_RMSE")
```
