---
title: "R Notebook"
output: html_notebook
---

```{r}
library(rjson)
library(tidyverse)
consumption <- fromJSON(file='/Users/andreasandersen/Desktop/data/consumption.json')
price <- fromJSON(file='/Users/andreasandersen/Desktop/data/prices.json')
prod_dist <- fromJSON(file='/Users/andreasandersen/Desktop/data/production_dist.json')
```

```{r}
consumption_df <- consumption$records %>%
  map_df(unlist) %>%
  arrange(HourUTC)
```

```{r}
price_df <- price$records %>%
  map_df(unlist) %>%
  arrange(HourUTC)
```

```{r}
prod_dist_df <- map_df(prod_dist, unlist) %>%
  arrange(HourUTC)
```


```{r}
n <- nrow(subset(price_df, price_df$PriceArea == 'DK1'))
subset(price_df, price_df$PriceArea == 'DK1')$HourUTC[1]
subset(price_df, price_df$PriceArea == 'DK1')$HourUTC[n]
as.Date(subset(price_df, price_df$PriceArea == 'DK1')$HourUTC[1])-as.Date(subset(price_df, price_df$PriceArea == 'DK1')$HourUTC[n])
```


```{r}
plot(1:n, price_df$SpotPriceDKK[price_df$PriceArea == 'DK1'], type='l')
```


```{r}
n <- nrow(subset(consumption_df, consumption_df$GridCompany=='003'))
subset(consumption_df, consumption_df$GridCompany=='003')$HourUTC[1]
subset(consumption_df, consumption_df$GridCompany=='003')$HourUTC[n]
as.Date(subset(consumption_df, consumption_df$GridCompany=='003')$HourUTC[1]) - as.Date(subset(consumption_df, consumption_df$GridCompany=='003')$HourUTC[n])
```

```{r}
plot(1:n, consumption_df$FlexSettledConsumption[consumption_df$GridCompany=='003'], type='l')

plot(1:n, consumption_df$FlexSettledConsumption[consumption_df$GridCompany=='003'], type='l', ylim=c(0, 200000))
```


```{r}
n <- nrow(subset(prod_dist_df, prod_dist_df$PriceArea=='DK1'))
subset(prod_dist_df, prod_dist_df$PriceArea=='DK1')$HourUTC[1]
subset(prod_dist_df, prod_dist_df$PriceArea=='DK1')$HourUTC[n]
as.Date(subset(prod_dist_df, prod_dist_df$PriceArea=='DK1')$HourUTC[1])-as.Date(subset(prod_dist_df, prod_dist_df$PriceArea=='DK1')$HourUTC[n])
```

```{r}
plot(1:n, as.numeric(prod_dist_df$TotalLoad[prod_dist_df$PriceArea == 'DK1']), type='l')
plot(1:n, as.numeric(prod_dist_df$TotalLoad[prod_dist_df$PriceArea == 'DK1']), type='l', ylim=c(0, 5000))
```






